name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Mis à jour en v4

      - name: Setup Python
        uses: actions/setup-python@v5 # Mis à jour en v5
        with:
          python-version: '3.10'

      - name: Install Flet
        run: |
          pip install flet

      - name: Build APK
        run: |
          # On crée le dossier assets s'il n'existe pas pour éviter les erreurs de build
          mkdir -p assets
          flet build apk --project "PikPikApp" --org "com.tonnom.pikpik"

      - name: Upload APK
        uses: actions/upload-artifact@v4 # LA CORRECTION : passage en v4
        with:
          name: pikpik-app-apk
          path: build/apk/*.apk
